export {
  DISSOLVE_MAX_MS,
  HOLD_FIRST_MS,
  REDUCED_MOTION_MS,
  clipMissing,
  createDomTransitionPlayer,
  dissolveDuration,
  dissolveFixesEncode,
  planTransition,
  playTransition,
  prefersReducedMotion,
  resetPlateTime,
  runTransition,
  smokeFailed,
  stillsMatch,
  transitionLoops,
  type DomTransitionEls,
  type DomTransitionPlayer,
  type JoinWarn,
  type PlanOpts,
  type RunOpts,
  type TransitionAct,
  type TransitionIO,
  type TransitionKind,
  type TransitionPlan,
  type TransitionPlate,
} from "./transition.ts";
