/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RuneRouteImport } from './routes/rune'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as WalkRouteImport } from './routes/walk'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiClipRouteImport } from './routes/api/clip'
import { Route as ApiDoorChatRouteImport } from './routes/api/door-chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RuneRoute = RuneRouteImport.update({
  id: '/rune',
  path: '/rune',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkRoute = WalkRouteImport.update({
  id: '/walk',
  path: '/walk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClipRoute = ApiClipRouteImport.update({
  id: '/api/clip',
  path: '/api/clip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDoorChatRoute = ApiDoorChatRouteImport.update({
  id: '/api/door-chat',
  path: '/api/door-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/login': typeof LoginRoute
  '/rune': typeof RuneRoute
  '/vault': typeof VaultRoute
  '/walk': typeof WalkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/clip': typeof ApiClipRoute
  '/api/door-chat': typeof ApiDoorChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/login': typeof LoginRoute
  '/rune': typeof RuneRoute
  '/vault': typeof VaultRoute
  '/walk': typeof WalkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/clip': typeof ApiClipRoute
  '/api/door-chat': typeof ApiDoorChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/login': typeof LoginRoute
  '/rune': typeof RuneRoute
  '/vault': typeof VaultRoute
  '/walk': typeof WalkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/clip': typeof ApiClipRoute
  '/api/door-chat': typeof ApiDoorChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/artifacts' | '/login' | '/rune' | '/vault' | '/walk' | '/api/auth/$' | '/api/clip' | '/api/door-chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/artifacts' | '/login' | '/rune' | '/vault' | '/walk' | '/api/auth/$' | '/api/clip' | '/api/door-chat'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/login'
    | '/rune'
    | '/vault'
    | '/walk'
    | '/api/auth/$'
    | '/api/clip'
    | '/api/door-chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRoute
  LoginRoute: typeof LoginRoute
  RuneRoute: typeof RuneRoute
  VaultRoute: typeof VaultRoute
  WalkRoute: typeof WalkRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiClipRoute: typeof ApiClipRoute
  ApiDoorChatRoute: typeof ApiDoorChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rune': {
      id: '/rune'
      path: '/rune'
      fullPath: '/rune'
      preLoaderRoute: typeof RuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk': {
      id: '/walk'
      path: '/walk'
      fullPath: '/walk'
      preLoaderRoute: typeof WalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clip': {
      id: '/api/clip'
      path: '/api/clip'
      fullPath: '/api/clip'
      preLoaderRoute: typeof ApiClipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/door-chat': {
      id: '/api/door-chat'
      path: '/api/door-chat'
      fullPath: '/api/door-chat'
      preLoaderRoute: typeof ApiDoorChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRoute,
  LoginRoute: LoginRoute,
  RuneRoute: RuneRoute,
  VaultRoute: VaultRoute,
  WalkRoute: WalkRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiClipRoute: ApiClipRoute,
  ApiDoorChatRoute: ApiDoorChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
